name: Security Scans
on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y bundler
          gem install bundler-audit

      - name: Run Bundler Audit
        run: |
          bundler-audit check --update
