name: Security Scans
on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Ensure latest version

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "railsgoat"
          format: "HTML"

      - name: Upload Security Report
        uses: actions/upload-artifact@v4  # Updated version
        with:
          name: security-report
          path: dependency-check-report.html
