name: Security Scans
on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Update Bundler
        run: |
          gem uninstall -aIx bundler
          gem install bundler -v 2.4.22 # Use latest Bundler

      - name: Install dependencies
        run: bundle _2.4.22_ install

      - name: Install Bundler Audit
        run: gem install bundler-audit

      - name: Run Bundler Audit
        run: bundle exec bundler-audit check --update

      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: bundler-audit.log
